[project]
name = "lamops"
version = "0.1.0"
description = "lambda ops"
authors = [
    {name = "ZeroAct",email = "lhj5682@naver.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "docstring-parser (>=0.16,<0.17)",
    "pydantic (>=2.10.6,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"
pytest = "^8.3.5"

